apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "demo-node"
  template:
    metadata:
      labels:
        app: demo-node
        track: stable
        version: 1.0.0
    spec:
      containers:
        - name: demo-node
          image: "braddle/demo-app:1.0.0"
          ports:
            - containerPort: 8080
